---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n0
  ip: 172.16.10.90
  join_ip: 172.16.10.91
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n1
  ip: 172.16.10.91
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n2
  ip: 172.16.10.92
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n3
  ip: 172.16.10.93
  join_ip: 172.16.10.91
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n4
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n4
  ip: 172.16.10.94
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n5
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n5
  ip: 172.16.10.95
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n6
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n6
  ip: 172.16.10.96
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n7
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n7
  ip: 172.16.10.97
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...
