---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node0
  ip: 172.16.10.90
  join_ip: 172.16.10.91
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node1
  ip: 172.16.10.91
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node2
  ip: 172.16.10.92
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node3
  ip: 172.16.10.93
  join_ip: 172.16.10.91
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node4
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node4
  ip: 172.16.10.94
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node5
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node5
  ip: 172.16.10.95
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node6
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node6
  ip: 172.16.10.96
  join_ip: 172.16.10.90
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...
