---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node0
  ip: 192.168.77.10
  join_ip: 192.168.77.11
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node1
  ip: 192.168.77.11
  join_ip: 192.168.77.10
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node2
  ip: 192.168.77.12
  join_ip: 192.168.77.10
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node3
  ip: 192.168.77.13
  join_ip: 192.168.77.11
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: node4
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: node4
  ip: 192.168.77.14
  join_ip: 192.168.77.10
  labels:
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...